version: '3'

tasks:
  format:
    desc: Format *go code
    vars:
      GO_FILES: "find . ! -path './vendor/*' -type f -name '*.go'"
    cmds:
      - ({{.GO_FILES}} | xargs gofmt -s -w)
      - ({{.GO_FILES}} | xargs golines -w --max-len=180 --reformat-tags --shorten-comments --ignore-generated)
      - go mod edit -fmt

  build:
    desc: local build
    cmds:
      - go build
      - mv btl ~/go/bin

  deploy:
    desc: deploy
    cmds:
      - GOOS=linux GOARCH=amd64 go build
      - scp btl beer:/tmp/btl
      - ssh beer '\mv /tmp/btl /root/go/bin/'
