package fit2gpx

var sportMap = map[string]string{
	"0":   "generic",
	"1":   "running",
	"2":   "cycling",
	"3":   "transition",
	"4":   "fitness_equipment",
	"5":   "swimming",
	"6":   "basketball",
	"7":   "soccer",
	"8":   "tennis",
	"9":   "american_football",
	"10":  "training",
	"11":  "walking",
	"12":  "cross_country_skiing",
	"13":  "alpine_skiing",
	"14":  "snowboarding",
	"15":  "rowing",
	"16":  "mountaineering",
	"17":  "hiking",
	"18":  "multisport",
	"19":  "paddling",
	"20":  "flying",
	"21":  "e_biking",
	"22":  "motorcycling",
	"23":  "boating",
	"24":  "driving",
	"25":  "golf",
	"26":  "hang_gliding",
	"27":  "horseback_riding",
	"28":  "hunting",
	"29":  "fishing",
	"30":  "inline_skating",
	"31":  "rock_climbing",
	"32":  "sailing",
	"33":  "ice_skating",
	"34":  "sky_diving",
	"35":  "snowshoeing",
	"36":  "snowmobiling",
	"37":  "stand_up_paddleboarding",
	"38":  "surfing",
	"39":  "wakeboarding",
	"40":  "water_skiing",
	"41":  "kayaking",
	"42":  "rafting",
	"43":  "windsurfing",
	"44":  "kitesurfing",
	"45":  "tactical",
	"46":  "jumpmaster",
	"47":  "boxing",
	"48":  "floor_climbing",
	"49":  "baseball",
	"53":  "diving",
	"62":  "hiit",
	"64":  "racket",
	"65":  "wheelchair_push_walk",
	"66":  "wheelchair_push_run",
	"67":  "meditation",
	"69":  "disc_golf",
	"71":  "cricket",
	"72":  "rugby",
	"73":  "hockey",
	"74":  "lacrosse",
	"75":  "volleyball",
	"76":  "water_tubing",
	"77":  "wakesurfing",
	"80":  "mixed_martial_arts",
	"82":  "snorkeling",
	"83":  "dance",
	"84":  "jump_rope",
	"254": "all",
	"255": "invalid",
}

func ParseSport(sportType string) string {
	sport, ok := sportMap[sportType]
	if ok {
		return sport
	}
	return "unknown"
}
